# Generated by Django 2.2.2 on 2019-06-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_chatimageinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='sig_id',
            field=models.IntegerField(null=True),
        ),
    ]
